"""
Abstract base class for trading strategies and plugin system.
"""

from abc import ABC, abstractmethod
from typing import Optional, Dict, Any, List
from dataclasses import dataclass
from datetime import datetime
import pandas as pd

from core.logger import get_logger
from data.models import OrderAction
from config import settings

logger = get_logger(__name__)


@dataclass
class SignalOutput:
    """Trading signal generated by a strategy."""
    
    action: OrderAction  # BUY or SELL
    symbol: str
    price: float
    stop_loss: float
    target: float
    confidence: float  # 0.0 to 1.0
    reason: str  # Explanation of why signal was generated
    timestamp: datetime = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.utcnow()
    
    @property
    def risk_reward_ratio(self) -> float:
        """Calculate risk:reward ratio."""
        if self.action == OrderAction.BUY:
            risk = self.price - self.stop_loss
            reward = self.target - self.price
        else:  # SELL
            risk = self.stop_loss - self.price
            reward = self.price - self.target
        
        return reward / risk if risk > 0 else 0.0
    
    def is_valid(self) -> bool:
        """Validate signal meets minimum requirements."""
        # Check risk:reward ratio
        if self.risk_reward_ratio < settings.trading.min_risk_reward:
            logger.warning(f"Signal rejected: R:R ratio {self.risk_reward_ratio:.2f} < {settings.trading.min_risk_reward}")
            return False
        
        # Check confidence
        if self.confidence < 0.5:
            logger.warning(f"Signal rejected: Low confidence {self.confidence:.2f}")
            return False
        
        # Validate prices
        if self.action == OrderAction.BUY:
            if self.stop_loss >= self.price or self.target <= self.price:
                logger.warning(f"Signal rejected: Invalid price levels for BUY")
                return False
        else:  # SELL
            if self.stop_loss <= self.price or self.target >= self.price:
                logger.warning(f"Signal rejected: Invalid price levels for SELL")
                return False
        
        return True


class Strategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    All strategies must inherit from this class and implement the required methods.
    """
    
    def __init__(self, name: str, description: str = None, parameters: Dict[str, Any] = None):
        """
        Initialize strategy.
        
        Args:
            name: Unique strategy name
            description: Strategy description
            parameters: Strategy-specific parameters
        """
        self.name = name
        self.description = description or ""
        self.parameters = parameters or {}
        
        # Performance tracking
        self.backtest_accuracy: Optional[float] = None
        self.backtest_sharpe: Optional[float] = None
        self.backtest_max_drawdown: Optional[float] = None
        self.is_validated: bool = False
        
        logger.info(f"Strategy initialized: {self.name}")
    
    @abstractmethod
    def generate_signal(self, symbol: str, data: pd.DataFrame) -> Optional[SignalOutput]:
        """
        Generate trading signal based on market data.
        
        Args:
            symbol: Stock ticker
            data: DataFrame with OHLCV data (index=timestamp, columns=open/high/low/close/volume)
        
        Returns:
            SignalOutput if signal generated, None otherwise
        """
        pass
    
    @abstractmethod
    def get_required_history(self) -> int:
        """
        Get number of historical periods (bars) required for strategy.
        
        Returns:
            Number of periods (e.g., 50 for 50-day SMA)
        """
        pass
    
    def validate_data(self, data: pd.DataFrame) -> bool:
        """
        Validate input data has required columns and sufficient history.
        
        Args:
            data: Input DataFrame
        
        Returns:
            True if valid, False otherwise
        """
        required_columns = ['open', 'high', 'low', 'close', 'volume']
        
        # Check columns
        if not all(col in data.columns for col in required_columns):
            logger.error(f"Missing required columns: {required_columns}")
            return False
        
        # Check history
        required_history = self.get_required_history()
        if len(data) < required_history:
            logger.warning(f"Insufficient history: {len(data)} < {required_history}")
            return False
        
        # Check for NaN values
        if data[required_columns].isna().any().any():
            logger.warning("Data contains NaN values")
            return False
        
        return True
    
    def is_tradeable(self) -> bool:
        """
        Check if strategy meets trading criteria.
        
        Returns:
            True if strategy can be used for live trading
        """
        if not self.is_validated:
            logger.warning(f"Strategy {self.name} is not validated")
            return False
        
        if self.backtest_accuracy is None:
            logger.warning(f"Strategy {self.name} has no backtest results")
            return False
        
        if self.backtest_accuracy < settings.trading.min_strategy_accuracy:
            logger.warning(
                f"Strategy {self.name} accuracy {self.backtest_accuracy:.2%} "
                f"< minimum {settings.trading.min_strategy_accuracy:.2%}"
            )
            return False
        
        return True
    
    def __str__(self) -> str:
        return f"Strategy({self.name})"
    
    def __repr__(self) -> str:
        return (
            f"<Strategy(name='{self.name}', validated={self.is_validated}, "
            f"accuracy={self.backtest_accuracy})>"
        )


class StrategyRegistry:
    """Registry for managing all trading strategies."""
    
    def __init__(self):
        self._strategies: Dict[str, Strategy] = {}
        logger.info("Strategy registry initialized")
    
    def register(self, strategy: Strategy):
        """
        Register a strategy.
        
        Args:
            strategy: Strategy instance
        """
        if strategy.name in self._strategies:
            logger.warning(f"Strategy {strategy.name} already registered, overwriting")
        
        self._strategies[strategy.name] = strategy
        logger.info(f"Registered strategy: {strategy.name}")
    
    def unregister(self, name: str):
        """
        Unregister a strategy.
        
        Args:
            name: Strategy name
        """
        if name in self._strategies:
            del self._strategies[name]
            logger.info(f"Unregistered strategy: {name}")
    
    def get(self, name: str) -> Optional[Strategy]:
        """
        Get strategy by name.
        
        Args:
            name: Strategy name
        
        Returns:
            Strategy instance or None
        """
        return self._strategies.get(name)
    
    def get_all(self) -> List[Strategy]:
        """Get all registered strategies."""
        return list(self._strategies.values())
    
    def get_tradeable(self) -> List[Strategy]:
        """Get all strategies that are validated and meet trading criteria."""
        return [s for s in self._strategies.values() if s.is_tradeable()]
    
    def list_names(self) -> List[str]:
        """Get list of all strategy names."""
        return list(self._strategies.keys())


# Global registry instance
registry = StrategyRegistry()
