"""
Database schema and ORM models using SQLAlchemy.
Replaces the old per-stock table design with normalized schema.
"""

from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Date, Boolean,
    ForeignKey, Index, UniqueConstraint, Enum as SQLEnum, Text
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
import enum


Base = declarative_base()


class Exchange(enum.Enum):
    """Stock exchange enum."""
    NSE = "NSE"
    BSE = "BSE"


class Timeframe(enum.Enum):
    """Price data timeframe."""
    MINUTE_1 = "1min"
    MINUTE_5 = "5min"
    MINUTE_15 = "15min"
    HOUR_1 = "1hour"
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"


class OrderAction(enum.Enum):
    """Order action types."""
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(enum.Enum):
    """Order status."""
    PENDING = "PENDING"
    PLACED = "PLACED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class TradingMode(enum.Enum):
    """Trading mode."""
    PAPER = "paper"
    LIVE = "live"


class Symbol(Base):
    """Stock symbols master table."""
    
    __tablename__ = "symbols"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, unique=True, index=True)
    company_name = Column(String(255), nullable=False)
    exchange = Column(SQLEnum(Exchange), nullable=False, default=Exchange.NSE)
    
    # Categorization
    is_nifty50 = Column(Boolean, default=False)
    is_fno = Column(Boolean, default=False)  # Futures & Options available
    is_active = Column(Boolean, default=True)
    
    # Metadata
    sector = Column(String(100))
    industry = Column(String(100))
    isin = Column(String(20))
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    prices = relationship("Price", back_populates="symbol", cascade="all, delete-orphan")
    signals = relationship("Signal", back_populates="symbol", cascade="all, delete-orphan")
    positions = relationship("Position", back_populates="symbol", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Symbol(symbol='{self.symbol}', company='{self.company_name}')>"


class Price(Base):
    """Price data for all symbols and timeframes (replaces per-stock tables)."""
    
    __tablename__ = "prices"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol_id = Column(Integer, ForeignKey("symbols.id", ondelete="CASCADE"), nullable=False)
    timestamp = Column(DateTime, nullable=False, index=True)
    
    # OHLCV data
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)
    
    # Additional fields
    timeframe = Column(SQLEnum(Timeframe), nullable=False, default=Timeframe.DAILY)
    turnover = Column(Float)
    
    # Relationships
    symbol = relationship("Symbol", back_populates="prices")
    
    # Composite unique constraint and indexes
    __table_args__ = (
        UniqueConstraint("symbol_id", "timestamp", "timeframe", name="uix_symbol_time_tf"),
        Index("idx_symbol_timeframe", "symbol_id", "timeframe"),
        Index("idx_timestamp", "timestamp"),
    )
    
    def __repr__(self):
        return f"<Price(symbol_id={self.symbol_id}, timestamp='{self.timestamp}', close={self.close})>"


class Strategy(Base):
    """Registered trading strategies."""
    
    __tablename__ = "strategies"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100), nullable=False, unique=True)
    description = Column(Text)
    
    # Strategy parameters (stored as JSON in practice, simplified here)
    parameters = Column(Text)  # JSON string of parameters
    
    # Performance metrics
    backtest_accuracy = Column(Float)  # Success rate from backtesting
    backtest_sharpe = Column(Float)
    backtest_max_drawdown = Column(Float)
    
    # Status
    is_active = Column(Boolean, default=True)
    is_validated = Column(Boolean, default=False)  # Passed backtesting validation
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    signals = relationship("Signal", back_populates="strategy", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Strategy(name='{self.name}', accuracy={self.backtest_accuracy})>"


class Signal(Base):
    """Trading signals generated by strategies."""
    
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_id = Column(Integer, ForeignKey("strategies.id", ondelete="CASCADE"), nullable=False)
    symbol_id = Column(Integer, ForeignKey("symbols.id", ondelete="CASCADE"), nullable=False)
    
    # Signal details
    action = Column(SQLEnum(OrderAction), nullable=False)  # BUY or SELL
    price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    target = Column(Float, nullable=False)
    
    # Metadata
    confidence = Column(Float)  # 0.0 to 1.0
    reason = Column(Text)  # Why the signal was generated
    
    # Status
    is_executed = Column(Boolean, default=False)
    executed_at = Column(DateTime)
    
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Relationships
    strategy = relationship("Strategy", back_populates="signals")
    symbol = relationship("Symbol", back_populates="signals")
    
    __table_args__ = (
        Index("idx_symbol_created", "symbol_id", "created_at"),
        Index("idx_strategy_created", "strategy_id", "created_at"),
    )
    
    def __repr__(self):
        return f"<Signal(action='{self.action}', symbol_id={self.symbol_id}, price={self.price})>"


class Order(Base):
    """Orders placed with broker."""
    
    __tablename__ = "orders"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=True)  # May be manual order
    
    # Order details
    symbol_id = Column(Integer, ForeignKey("symbols.id", ondelete="CASCADE"), nullable=False)
    action = Column(SQLEnum(OrderAction), nullable=False)
    quantity = Column(Integer, nullable=False)
    price = Column(Float, nullable=False)
    
    # Broker details
    broker_order_id = Column(String(100), unique=True)  # Broker's order ID
    status = Column(SQLEnum(OrderStatus), nullable=False, default=OrderStatus.PENDING)
    
    # Execution details
    filled_quantity = Column(Integer, default=0)
    average_price = Column(Float)
    
    # Metadata
    trading_mode = Column(SQLEnum(TradingMode), nullable=False, default=TradingMode.PAPER)
    error_message = Column(Text)
    
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    executed_at = Column(DateTime)
    
    __table_args__ = (
        Index("idx_status_created", "status", "created_at"),
    )
    
    def __repr__(self):
        return f"<Order(action='{self.action}', symbol_id={self.symbol_id}, status='{self.status}')>"


class Position(Base):
    """Current and historical positions."""
    
    __tablename__ = "positions"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol_id = Column(Integer, ForeignKey("symbols.id", ondelete="CASCADE"), nullable=False)
    
    # Position details
    quantity = Column(Integer, nullable=False)
    entry_price = Column(Float, nullable=False)
    current_price = Column(Float, nullable=False)
    stop_loss = Column(Float)
    target = Column(Float)
    
    # P&L
    realized_pnl = Column(Float, default=0.0)
    unrealized_pnl = Column(Float, default=0.0)
    
    # Status
    is_open = Column(Boolean, default=True, index=True)
    trading_mode = Column(SQLEnum(TradingMode), nullable=False, default=TradingMode.PAPER)
    
    # Timestamps
    entry_time = Column(DateTime, default=datetime.utcnow)
    exit_time = Column(DateTime)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    symbol = relationship("Symbol", back_populates="positions")
    
    __table_args__ = (
        Index("idx_symbol_open", "symbol_id", "is_open"),
    )
    
    def __repr__(self):
        return f"<Position(symbol_id={self.symbol_id}, quantity={self.quantity}, is_open={self.is_open})>"


class BacktestResult(Base):
    """Backtest results for strategies."""
    
    __tablename__ = "backtest_results"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_id = Column(Integer, ForeignKey("strategies.id", ondelete="CASCADE"), nullable=False)
    
    # Test parameters
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    initial_capital = Column(Float, nullable=False)
    
    # Performance metrics
    final_capital = Column(Float, nullable=False)
    total_trades = Column(Integer, nullable=False)
    winning_trades = Column(Integer, nullable=False)
    losing_trades = Column(Integer, nullable=False)
    accuracy = Column(Float, nullable=False)  # Win rate
    
    # Risk metrics
    sharpe_ratio = Column(Float)
    sortino_ratio = Column(Float)
    max_drawdown = Column(Float)
    max_drawdown_duration = Column(Integer)  # Days
    
    # Returns
    total_return = Column(Float)  # %
    annual_return = Column(Float)  # %
    
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    def __repr__(self):
        return f"<BacktestResult(strategy_id={self.strategy_id}, accuracy={self.accuracy})>"


class Alert(Base):
    """Alerts and notifications sent to user."""
    
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Alert details
    type = Column(String(50), nullable=False)  # signal, error, warning, info
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    
    # Delivery
    email_sent = Column(Boolean, default=False)
    sms_sent = Column(Boolean, default=False)
    
    # Extra data
    extra_data = Column(Text)  # JSON string for additional data
    
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    def __repr__(self):
        return f"<Alert(type='{self.type}', title='{self.title}')>"
